home/urls.py
import os

from django.conf.urls import url
from django.views.static import serve

from . import views

urlpatterns = [
    url(r'^settings.py$', serve, {
        'path': 'settings.py',
        'document_root': os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    }, name='settings.py'),
    url(r'^$', views.index, name='index'),
    url(r'^docs/$', views.docs, name='docs'),
    url(r'^demos/$', views.demos, name='demos'),
    url(r'^about/$', views.about, name='about'),
    url(r'^license/$', views.license, name='license'),
    url(r'^favicon.ico$', serve, {
        'path': 'favicon.ico',
        'document_root': os.path.join(os.path.dirname(os.path.abspath(__file__)), 'static')
    }, name='favicon.ico'),
]

mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^', include('home.urls', namespace='home')),
    url(r'^utils/', include('myutils.urls', namespace='utils')),
    url(r'^stats/', include('site_stats.urls', namespace='stats')),
    url(r'^celery/', include('celery_test.urls', namespace='celery')),
    url(r'^upload/', include('file_upload.urls', namespace='upload')),
    url(r'^go/', include('golang.urls', namespace='golang')),
    url(r'^bkapi/', include('blueking_api.urls', namespace='bkapi')),
    url(r'^mail/', include('send_email.urls', namespace='mail')),
    url(r'^ws/', include('websocket_test.urls', namespace='ws')),
    url(r'^admin/', include(admin.site.urls)),
]

myutils/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^pyinfo/$', views.pyinfo, name='pyinfo'),
    url(r'^process/$', views.process, name='process'),
    url(r'^netstat/$', views.netstat, name='netstat'),
    url(r'^debug/$', views.debug_, name='debug'),
    url(r'^files/$', views.files, name='files'),
    url(r'^createsuperuser/$', views.manage_createsuperuser, name='createsuperuser'),
    url(r'^reset_db/$', views.manage_reset_db, name='reset_db'),
    url(r'^500/$', views.raise_500, name='raise_500'),
]

home/views.py
# coding=utf-8
from .utils import render_markdown_template, render_plain_text_file, render_special_markdown_template


def index(request):
    return render_special_markdown_template(request, 'home/index.html', 'docs/getting-started.md')


def about(request):
    return render_markdown_template(request, u'About', u'关于蓝鲸云平台', 'docs/about.md')


def docs(request):
    return render_markdown_template(request,
                                    u'Documentations',
                                    u'A Django Startup Project For Tencent Blueking',
                                    'docs/docs.md',
                                    (
                                        u'A Simplified Django Settings For Tencent Blueking',
                                    ))


def demos(request):
    return render_markdown_template(request, u'Online Demos', u'在线演示', 'docs/demos.md')


def license(request):
    return render_plain_text_file(request, u'License', u'The MIT License', 'LICENSE')

home/templates/home/admin_db_reset.html
<form method="POST">
    {% csrf_token %}
    <label for="password">Password:</label>
    <input type="text" name="password" id="password">
    <input type="submit">
</form>
<p>{{ message }}</p>

home/templates/home/base.html
{% load static from staticfiles %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %}{% endblock %}A Django Startup Project For Tencent Blueking</title>
    <link rel="icon" sizes="192x192" href="{% static "home/images/favicon.png" %}">
    <link rel="stylesheet" href="{% static "home/css/bootstrap.min.css" %}">
    <link rel="stylesheet" href="{% static "home/css/github-markdown.css" %}">
    <link rel="stylesheet" href="{% static "home/css/index.css" %}">
    {% block head_append %}{% endblock %}
</head>
<body>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark">
        <div class="container">
            <a class="navbar-brand" href="/">蓝鲸 Django 项目起始模板</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item{% if navbar.index %} active{% endif %}">
                        <a class="nav-link" href="{% url 'home:index' %}">首页</a>
                    </li>
                    <li class="nav-item{% if navbar.docs %} active{% endif %}">
                        <a class="nav-link" href="{% url 'home:docs' %}">文档</a>
                    </li>
                    <li class="nav-item{% if navbar.bkapi %} active{% endif %}">
                        <a class="nav-link" href="/bkapi/">蓝鲸API</a>
                    </li>
                    <li class="nav-item{% if navbar.demos %} active{% endif %}">
                        <a class="nav-link" href="{% url 'home:demos' %}">演示</a>
                    </li>
                    <li class="nav-item{% if navbar.about %} active{% endif %}">
                        <a class="nav-link" href="{% url 'home:about' %}">关于</a>
                    </li>
                </ul>
                <ul class="navbar-nav">
                    {% if not request.session.nick_name %}
                        <li class="nav-item">
                            <a class="nav-link" target="_blank" href="https://bk.tencent.com/campus/developer-center/">蓝鲸开发者中心</a>
                        </li>
                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link" target="_blank" href="https://bk.tencent.com/campus/developer-center/"><span class="mr-2">{{ request.session.nick_name }}</span><img src="{{ request.session.avatar_url }}" class="avatar-img" alt="avatar"></a>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>

    <div class="jumbotron jumbotron-fluid">
        <div class="blueking-background d-none d-md-block">
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 26.872 20.359" height="240" width="320">
                <path d="M8.294 3.818c-.73-.61-1.54-1.05-2.298-.712L5.903 1.44c.408-.094 1.637-.209 2.157.84C8.348 1.005 9.192.12 9.483.131l.152 1.657c-.691.166-1.056 1.022-1.341 2.029zM23.21 20.18l.933-1.12-19.266.047c-6.06-2.03-2.74-9.656-1.213-11.476C5.19 5.812 6.495 4.6 8.935 4.739c5.71.327 6.994 5.688 7.138 7.93.144 2.244 1.827 4.626 3.498 5.179 1.672.553 3.951-.076 5.35-1.345 1.398-1.269 2.54-4.363 1.256-7.31-1.351-2.684-3.644-3.704-4.858-3.68-.06-4.199-3.528-5.001-5.38-4.994-1.853.007-4.578 2.914-4.578 2.914s3.892-4.078 7.415-.51c1.357 1.375 1.314 2.223 1.179 3.751.822-.021 2.46-.074 4.35 2.446 1.043 1.39 2.19 5.202.198 6.84-1.027.844-2.718.938-3.985.538-1.808-.572-2.924-2.588-3.092-3.949-.302-2.44-.218-6.72-4.852-8.416-5.893-2.158-9.47 3.265-9.47 3.265S-.583 12.62.258 16.355c.842 3.735 3.639 3.872 3.639 3.872z" />
            </svg>
        </div>
        <div class="container">
            {% block jumbotron %}{% endblock %}
        </div>
    </div>

    {% block main %}{% endblock %}

    <footer class="navbar navbar-expand-md navbar-dark bg-dark mt-4">
        <div class="container">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <span class="navbar-text">Copyright &copy; 2018 Ganlv</span>
                </li>
                <li class="nav-item{% if navbar.license %} active{% endif %}">
                    <a class="nav-link" href="{% url 'home:license' %}">MIT License</a>
                </li>
                <li class="nav-item visit-count">
                    <a class="nav-link" href="/stats/">Visit counter: {{ visit_count }}</a>
                </li>
            </ul>
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" target="_blank" href="https://bk.tencent.com/campus/developer-center/">蓝鲸开发者中心</a>
                </li>
            </ul>
        </div>
    </footer>

    <script src="{% static "home/js/jquery-3.3.1.slim.min.js" %}"></script>
    <script src="{% static "home/js/bootstrap.bundle.min.js" %}"></script>
    {% if REMOTE_STATIC_URL %}
        <script src="{{ REMOTE_STATIC_URL }}v3/analysis.js"></script>
    {% endif %}
    {% block body_append %}{% endblock %}
</body>
</html>

home/templates/home/index.html
{% extends "home/base.html" %}

{% block jumbotron %}
    <h1 class="mb-4">蓝鲸 Django 项目起始模板</h1>
    <p class="lead mb-4">使用一个简化的 <a href="{% url 'utils:files' %}?path=./settings.py" target="_blank" rel="noopener"><code>settings.py</code></a>，让原生 Django 项目可以运行在蓝鲸智云上。</p>
    <p class="small">你可能认为蓝鲸智云的默认 Django 项目有很多使用不到的配置、不利于初学者学习的配置。</p>
    <p class="small">这个仓库为您提供一个 <code>settings.py</code>，使用它即可使一个原生 Django 项目运行在蓝鲸智云上。</p>
    <p class="small">你也可以克隆这个示例仓库，作为一个项目的模板。但是请注意，整个仓库的精华就在 <code>settings.py</code> 中。</p>
{% endblock %}

{% block main %}
    <div class="container">
        <div class="content">
            <h2 class="text-center my-4">开始使用</h2>
            <div class="markdown-body">
                {{ content|safe }}
            </div>
            <div class="text-center my-4">
                <a href="{% url 'home:docs' %}" class="btn btn-outline-primary btn-lg px-md-5">了解更多</a>
            </div>
        </div>
    </div>
{% endblock %}

home/templates/home/markdown.html
{% extends "home/base.html" %}

{% block title %}{{ title }} - {% endblock %}

{% block jumbotron %}
    {% if leads %}
        <h1 class="mb-4">{{ heading }}</h1>
        {% for lead in leads %}
            <p class="lead">{{ lead }}</p>
        {% endfor %}
    {% else %}
        <h1>{{ heading }}</h1>
    {% endif %}
{% endblock %}

{% block main %}
    <div class="container">
        <div class="markdown-body">
            {{ content|safe }}
        </div>
    </div>
{% endblock %}

home/templates/home/plain_text.html
{% extends "home/base.html" %}

{% block title %}{{ title }} - {% endblock %}

{% block head_append %}
    <style>
        pre {
            padding: 16px;
            overflow: auto;
            font-size: 85%;
            line-height: 1.45;
            background-color: #f6f8fa;
            border-radius: 3px;
        }
    </style>
{% endblock %}

{% block jumbotron %}
    <h1>{{ heading }}</h1>
{% endblock %}

{% block main %}
    <div class="container">
        <pre><code>{{ content }}</code></pre>
    </div>
{% endblock %}