home/urls.py
import os

from django.conf.urls import url
from django.views.static import serve

from . import views

urlpatterns = [
    url(r'^settings.py$', serve, {
        'path': 'settings.py',
        'document_root': os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    }, name='settings.py'),
    url(r'^$', views.index, name='index'),
    url(r'^docs/$', views.docs, name='docs'),
    url(r'^demos/$', views.demos, name='demos'),
    url(r'^about/$', views.about, name='about'),
    url(r'^license/$', views.license, name='license'),
    url(r'^favicon.ico$', serve, {
        'path': 'favicon.ico',
        'document_root': os.path.join(os.path.dirname(os.path.abspath(__file__)), 'static')
    }, name='favicon.ico'),
]

mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^', include('home.urls', namespace='home')),
    url(r'^utils/', include('myutils.urls', namespace='utils')),
    url(r'^stats/', include('site_stats.urls', namespace='stats')),
    url(r'^celery/', include('celery_test.urls', namespace='celery')),
    url(r'^upload/', include('file_upload.urls', namespace='upload')),
    url(r'^go/', include('golang.urls', namespace='golang')),
    url(r'^bkapi/', include('blueking_api.urls', namespace='bkapi')),
    url(r'^mail/', include('send_email.urls', namespace='mail')),
    url(r'^ws/', include('websocket_test.urls', namespace='ws')),
    url(r'^admin/', include(admin.site.urls)),
]

send_email/views.py
# coding=utf-8
import re

from django.core.mail import send_mail
from django.core.mail.backends.smtp import EmailBackend
from django.shortcuts import render
from django.template.loader import get_template


def index(request):
    html_template = get_template('send_email/email.html')
    subject = 'Hello from django.qcloudapps.com'
    content = 'A Django Startup Project For Tencent Blueking.\n' \
              'A Simplified Django Settings For Tencent Blueking.\n' \
              'Home Page https://django.qcloudapps.com/'

    html_content = html_template.render({
        'title': subject,
        'lines': content.split('\n'),
    })
    html_content = re.sub(r'\s+', ' ', html_content)

    if request.method == 'GET':
        return render(request, 'send_email/index.html', {
            'email': html_content
        })

    host = request.POST.get('host')
    port = int(request.POST.get('port'))
    username = request.POST.get('username')
    password = request.POST.get('password')
    email = request.POST.get('email')
    if not username or not password:
        return render(request, 'send_email/index.html', {
            'error': u'未设置 SMTP 账号，发送邮件失败'
        })

    try:
        connection = EmailBackend(
            host=host,
            port=port,
            username=username,
            password=password
        )
        send_mail(
            subject,
            content,
            username,
            [email],
            html_message=html_content,
            connection=connection
        )
    except Exception as e:
        return render(request, 'send_email/index.html', {
            'error': e.message
        })

    return render(request, 'send_email/index.html', {
        'ok': True
    })

send_email/templates/send_email/email.html
<div style="
    width: 640px;
    box-shadow: 1px 3px 4px rgba(0, 0, 0, 0.2);
">
    <h1 style="
        margin: 0;
        padding: 1em;
        color: #047;
        background: rgba(50, 210, 130, 0.2);
        text-align: center;
    ">{{ title }}</h1>
    <div style="
        padding: 1em;
        text-indent: 2em;
    ">
        {% for line in lines %}
            <p>{{ line }}</p>
        {% endfor %}
    </div>
</div>

send_email/templates/send_email/index.html
{% extends "home/base.html" %}

{% block title %}Send Email - {% endblock %}

{% block jumbotron %}
    <h1>发送邮件</h1>
{% endblock %}

{% block main %}
    <div class="container">
        <div class="row justify-content-lg-center">
            {% if email %}
                <div class="mb-4">
                    {{ email|safe }}
                </div>
            {% endif %}

            <div class="col-lg-8">
                <div class="alert alert-info" role="alert">
                    演示服务器不内置 SMTP 账号，你需要输入你自己的 SMTP 账号密码来发送邮件，我们不会保存你的任何账号信息
                </div>
                {% if ok %}
                    <div class="alert alert-success" role="alert">
                        邮件已发送
                    </div>
                {% elif error %}
                    <div class="alert alert-danger" role="alert">
                        {{ error }}
                    </div>
                    <div class="text-center">
                        <a href="{% url 'mail:index' %}" class="btn btn-primary px-5">返回</a>
                    </div>
                {% else %}
                    <form method="post">
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="form-input-host">SMTP 服务器</label>
                            <input type="text" name="host" value="smtp.qq.com" class="form-control" id="form-input-host" placeholder="请输入 SMTP 服务器">
                        </div>
                        <div class="form-group">
                            <label for="form-input-port">SMTP 服务端口</label>
                            <input type="text" name="port" value="25" class="form-control" id="form-input-port" placeholder="请输入 SMTP 端口">
                        </div>
                        <div class="form-group">
                            <label for="form-input-username">SMTP 账号</label>
                            <input type="text" name="username" value="@qq.com" class="form-control" id="form-input-username" placeholder="请输入 SMTP 账号">
                        </div>
                        <div class="form-group">
                            <label for="form-input-password">SMTP 密码</label>
                            <input type="password" name="password" class="form-control" id="form-input-password" placeholder="请输入 SMTP 密码">
                        </div>
                        <div class="form-group">
                            <label for="form-input-email">目标邮箱</label>
                            <input type="text" name="email" class="form-control" id="form-input-email" placeholder="请输入目标邮箱">
                        </div>
                        <div class="text-center">
                            <button type="submit" class="btn btn-primary px-5">发送</button>
                        </div>
                    </form>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}