celery_test/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^status/$', views.status, name='status'),
    url(r'^add/$', views.add, name='add'),
    url(r'^$', views.index, name='index'),
]

home/urls.py
import os

from django.conf.urls import url
from django.views.static import serve

from . import views

urlpatterns = [
    url(r'^settings.py$', serve, {
        'path': 'settings.py',
        'document_root': os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    }, name='settings.py'),
    url(r'^$', views.index, name='index'),
    url(r'^docs/$', views.docs, name='docs'),
    url(r'^demos/$', views.demos, name='demos'),
    url(r'^about/$', views.about, name='about'),
    url(r'^license/$', views.license, name='license'),
    url(r'^favicon.ico$', serve, {
        'path': 'favicon.ico',
        'document_root': os.path.join(os.path.dirname(os.path.abspath(__file__)), 'static')
    }, name='favicon.ico'),
]

mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^', include('home.urls', namespace='home')),
    url(r'^utils/', include('myutils.urls', namespace='utils')),
    url(r'^stats/', include('site_stats.urls', namespace='stats')),
    url(r'^celery/', include('celery_test.urls', namespace='celery')),
    url(r'^upload/', include('file_upload.urls', namespace='upload')),
    url(r'^go/', include('golang.urls', namespace='golang')),
    url(r'^bkapi/', include('blueking_api.urls', namespace='bkapi')),
    url(r'^mail/', include('send_email.urls', namespace='mail')),
    url(r'^ws/', include('websocket_test.urls', namespace='ws')),
    url(r'^admin/', include(admin.site.urls)),
]

celery_test/models.py
from django.db import models


class Counter(models.Model):
    value = models.IntegerField(default=0)

    class Meta:
        app_label = 'celery_test'

celery_test/views.py
from django.shortcuts import render
from djcelery.models import TaskMeta

from . import tasks
from .models import Counter


def index(request):
    counter = Counter.objects.first()
    value = counter.value
    return render(request, 'celery_test/index.html', {
        'count': value
    })


def add(request):
    result = tasks.add.delay()
    return render(request, 'celery_test/add.html', {
        'task_id': str(result)
    })


def status(request):
    task_id = request.GET.get('task_id')
    task_meta = TaskMeta.objects.filter(task_id=task_id).first()
    return render(request, 'celery_test/status.html', {
        'task_id': task_id,
        'task_meta': task_meta,
    })

celery_test/templates/celery_test/add.html
{% extends "home/base.html" %}

{% block title %}Celery - {% endblock %}

{% block jumbotron %}
    <h1 class="mb-4">立刻 +1</h1>
    <p>发送一个后台任务给 Celery</p>
{% endblock %}

{% block main %}
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <h2 class="text-center my-4">任务 id</h2>
                <div class="card my-4">
                    <div class="card-body">
                        <p class="text-center"><a href="{% url 'celery:status' %}?task_id={{ task_id }}">{{ task_id }}</a></p>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

celery_test/templates/celery_test/index.html
{% extends "home/base.html" %}

{% block title %}Celery - {% endblock %}

{% block jumbotron %}
    <h1 class="mb-4">Celery</h1>
    <p>一个每分钟 +1 的计数器</p>
{% endblock %}

{% block main %}
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <h2 class="text-center my-4">计数器</h2>
                <div class="card my-4">
                    <div class="card-body">
                        <p class="display-4 text-center">{{ count }}</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

celery_test/templates/celery_test/status.html
{% extends "home/base.html" %}

{% block title %}Celery - {% endblock %}

{% block head_append %}
    <style>
        pre {
            padding: 16px;
            overflow: auto;
            font-size: 85%;
            line-height: 1.45;
            background-color: #f6f8fa;
            border-radius: 3px;
        }
    </style>
{% endblock %}

{% block jumbotron %}
    <h1 class="mb-4">任务状态</h1>
    <p>你可以连续刷新这个页面，直到出现结果。</p>
{% endblock %}

{% block main %}
    <div class="container">
        <div class="table-responsive my-4">
            <table class="table table-hover table-bordered">
                <tbody>
                    <tr>
                        <td>任务 id</td>
                        <td>{{ task_id }}</td>
                    </tr>
                    {% if task_meta %}
                        <tr>
                            <td>状态</td>
                            <td>{{ task_meta.status }}</td>
                        </tr>
                        <tr>
                            <td>结果</td>
                            <td>{{ task_meta.result }}</td>
                        </tr>
                        <tr>
                            <td>完成时间</td>
                            <td>{{ task_meta.date_done }}</td>
                        </tr>
                        <tr>
                            <td>元数据</td>
                            <td>
                                <pre><code>{{ task_meta.meta }}</code></pre>
                            </td>
                        </tr>
                    {% else %}
                        <tr>
                            <td>状态</td>
                            <td>该任务不存在或暂时未被处理</td>
                        </tr>
                        <tr>
                            <td>结果</td>
                            <td>-</td>
                        </tr>
                        <tr>
                            <td>完成时间</td>
                            <td>-</td>
                        </tr>
                        <tr>
                            <td>元数据</td>
                            <td>-</td>
                        </tr>
                    {% endif %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}