file_upload/urls.py
from django.conf.urls import url
from django.views.static import serve

from mysite import settings
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^delete/$', views.delete, name='delete'),
    url(r'^(?P<path>.*)$', serve, {
        'document_root': settings.MEDIA_ROOT,
    }, name='serve'),
]

home/urls.py
import os

from django.conf.urls import url
from django.views.static import serve

from . import views

urlpatterns = [
    url(r'^settings.py$', serve, {
        'path': 'settings.py',
        'document_root': os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    }, name='settings.py'),
    url(r'^$', views.index, name='index'),
    url(r'^docs/$', views.docs, name='docs'),
    url(r'^demos/$', views.demos, name='demos'),
    url(r'^about/$', views.about, name='about'),
    url(r'^license/$', views.license, name='license'),
    url(r'^favicon.ico$', serve, {
        'path': 'favicon.ico',
        'document_root': os.path.join(os.path.dirname(os.path.abspath(__file__)), 'static')
    }, name='favicon.ico'),
]

mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^', include('home.urls', namespace='home')),
    url(r'^utils/', include('myutils.urls', namespace='utils')),
    url(r'^stats/', include('site_stats.urls', namespace='stats')),
    url(r'^celery/', include('celery_test.urls', namespace='celery')),
    url(r'^upload/', include('file_upload.urls', namespace='upload')),
    url(r'^go/', include('golang.urls', namespace='golang')),
    url(r'^bkapi/', include('blueking_api.urls', namespace='bkapi')),
    url(r'^mail/', include('send_email.urls', namespace='mail')),
    url(r'^ws/', include('websocket_test.urls', namespace='ws')),
    url(r'^admin/', include(admin.site.urls)),
]

file_upload/views.py
import os

from django.core.exceptions import ValidationError
from django.core.files.storage import FileSystemStorage
from django.core.urlresolvers import reverse
from django.http.response import HttpResponseBadRequest, HttpResponseRedirect
from django.shortcuts import render

from mysite import settings
from myutils.utils import format_time
from .utils import sanitize_path


def index(request):
    if request.method == 'POST' and request.FILES['file']:
        """Simple File Upload
        https://github.com/sibtc/simple-file-upload
        """
        myfile = request.FILES['file']
        fs = FileSystemStorage()
        filename = fs.save(myfile.name, myfile)
        uploaded_file_url = fs.url(filename)
        return render(request, 'file_upload/index.html', {
            'ok': True,
            'uploaded_file_url': uploaded_file_url,
        })

    document_root = settings.MEDIA_ROOT.decode('utf-8')

    _files = []

    if os.path.exists(document_root):
        file_names = os.listdir(document_root)
        for filename in file_names:
            full_path = os.path.join(document_root, filename)
            file_stat = os.stat(full_path)
            _files.append({
                'name': filename,
                'mode': oct(file_stat.st_mode & 0o777),
                'size': file_stat.st_size,
                'date': format_time(file_stat.st_mtime)
            })

    return render(request, 'file_upload/index.html', {
        'files': _files
    })


def delete(request):
    if request.method != 'DELETE' and (request.method != 'POST' or request.POST.get('_method') != 'DELETE'):
        return HttpResponseRedirect(reverse('upload:index'))

    path = request.POST.get('path')
    if not path:
        raise ValidationError('path must be set')

    newpath = sanitize_path(path)
    if newpath and path != newpath:
        return HttpResponseBadRequest('path should be {} instead of {}'.format(newpath, path))

    document_root = settings.MEDIA_ROOT
    fullpath = os.path.join(document_root, newpath)

    if not os.path.exists(fullpath):
        return HttpResponseRedirect(reverse('upload:index'))

    os.unlink(fullpath)
    return render(request, 'file_upload/delete.html', {
        'file_deleted': path,
    })

file_upload/templates/file_upload/delete.html
{% extends "home/base.html" %}

{% block title %}Delete Uploaded File- {% endblock %}

{% block jumbotron %}
    <h1>删除上传的文件</h1>
{% endblock %}

{% block main %}
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <div class="alert alert-success" role="alert">
                    文件 {{ file_deleted }} 已删除
                </div>
                <div class="text-center">
                    <div class="text-center">
                        <a href="{% url 'upload:index' %}" class="btn btn-outline-primary px-5">返回</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

file_upload/templates/file_upload/index.html
{% extends "home/base.html" %}

{% block title %}Upload File - {% endblock %}

{% block head_append %}
    <style>
        td:nth-child(2) {
            width: 4em;
            max-width: 4em;
        }

        td:nth-last-child(3) {
            width: 4em;
            max-width: 4em;
        }

        td:nth-last-child(2) {
            width: 5em;
            max-width: 5em;
        }

        td:nth-last-child(1) {
            width: 10em;
            max-width: 10em;
        }
    </style>
{% endblock %}

{% block jumbotron %}
    <h1 class="mb-4">上传文件</h1>
    <div class="row">
        <div class="col-md-8 col-lg-6">
            <div class="card">
                <div class="card-body">
                    <form action="{% url 'upload:index' %}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-group">
                            <input type="file" name="file" class="form-control-file" id="form-input-file">
                        </div>
                        <div>
                            <button type="submit" class="btn btn-primary px-5">上传</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block main %}
    <div class="container">
        {% if ok %}
            <div class="row justify-content-center">
                <div class="col-md-6">
                    <div class="alert alert-success" role="alert">
                        上传成功 <a href="{{ uploaded_file_url }}">{{ uploaded_file_url }}</a>
                    </div>
                    <div class="text-center">
                        <div class="text-center">
                            <a href="{% url 'upload:index' %}" class="btn btn-outline-primary px-5">返回</a>
                        </div>
                    </div>
                </div>
            </div>
        {% else %}
            <h2 class="mb-4 text-center">已上传文件</h2>
            <div class="table-responsive">
                <table class="table table-striped table-hover table-sm">
                    <thead>
                        <tr>
                            <th>文件名</th>
                            <th>删除</th>
                            <th>模式</th>
                            <th>大小</th>
                            <th>修改时间</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for file in files %}
                            <tr>
                                <td><a href="{% url 'upload:serve' file.name %}">{{ file.name }}</a></td>
                                <td>
                                    <form action="{% url 'upload:delete' %}" method="post">
                                        {% csrf_token %}
                                        <input type="hidden" name="_method" value="DELETE">
                                        <input type="hidden" name="path" value="{{ file.name }}">
                                        <input type="submit" value="删除">
                                    </form>
                                </td>
                                <td>{{ file.mode }}</td>
                                <td>{{ file.size }}</td>
                                <td>{{ file.date }}</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        {% endif %}
    </div>
{% endblock %}